version: '3.8'

services:

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: ${GITLAB_HOSTNAME}
    container_name: gitlab
    environment:
      TZ: ${TZ}
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${GITLAB_HOSTNAME}'
        registry_external_url 'https://${GITLAB_HOSTNAME}:${GITLAB_REGISTRY_PORT}'
        gitlab_rails['initial_root_password'] = '${GITLAB_ROOT_PASSWORD}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
        letsencrypt['enable'] = true
        letsencrypt['contact_emails'] = ['amirhebrahimzader@gmail.com']
    ports:
      - '443:443'
      - '80:80'
      - '${GITLAB_SSH_PORT}:22'
      - '${GITLAB_REGISTRY_PORT}:5050'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    shm_size: '256m'


  runner:
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    container_name: gitlab-runner
    depends_on:
      - gitlab
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './gitlab-runner/config:/etc/gitlab-runner'



#Hints: first start gitlab, then runner; register runner manually via token, tags, etc.
#then u can use it for ur cicd and ENJOY.
